[package]
name = "ddd4r-sample-javalin-satoken"
description = "ddd4r compatibility package for ddd4j-sample-javalin-satoken"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
publish = false

[dependencies]
ddd4r-core = { path = "../../../crates/ddd4r-core", version = "=0.1.0-alpha.1" }

[lints]
workspace = true
