[package]
name = "ddd4r-data-rbatis"
description = "ddd4r compatibility package for ddd4j-data-mybatis"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
publish = false

[features]
default = []
memcached-cache = ["dep:rbatis-memcached"]
r2dbc = ["dep:rbatis-r2dbc"]

[dependencies]
ddd4r-core = { path = "../../../crates/ddd4r-core", version = "=0.1.0-alpha.1" }
ddd4r-data = { path = "../ddd4r-data", version = "=0.1.0-alpha.1" }
futures.workspace = true
rbatis.workspace = true
rbatis-memcached = { workspace = true, optional = true }
rbatis-r2dbc = { workspace = true, optional = true }
rbatis-typehandlers-jsr310.workspace = true
rbdc-sqlite.workspace = true
rbs.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
tokio.workspace = true

[lints]
workspace = true
