[package]
name = "ddd4r-data-rbatis"
description = "ddd4r compatibility package for ddd4j-data-mybatis"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
publish = false

[dependencies]
ddd4r-core = { path = "../../../crates/ddd4r-core", version = "=0.1.0-alpha.1" }
ddd4r-data = { path = "../ddd4r-data", version = "=0.1.0-alpha.1" }
futures.workspace = true
rbatis.workspace = true
rbatis-typehandlers-jsr310 = { git = "https://github.com/rbatis-plus/rbatis-typehandlers-jsr310.git", rev = "ac285d0b858738776362ff60368ba39638d08926" }
rbdc-sqlite.workspace = true
rbs.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
tokio.workspace = true

[lints]
workspace = true
