[package]
name = "ddd4r-diagnostics-pprof"
description = "Explicitly compiled and authorized CPU pprof diagnostics for ddd4r"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
ddd4r-diagnostics = { path = "../ddd4r-diagnostics", version = "=0.1.0-alpha.1" }
tokio.workspace = true

[target.'cfg(unix)'.dependencies]
pprof.workspace = true

[lints]
workspace = true
