[package]
name = "ddd4r-mq-disruptor"
description = "ddd4r compatibility package for ddd4j-mq-disruptor"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
publish = false

[dependencies]
dashmap.workspace = true
ddd4r-core = { path = "../../../crates/ddd4r-core", version = "=0.1.0-alpha.1" }
ddd4r-mq-core = { path = "../ddd4r-mq-core", version = "=0.1.0-alpha.1" }
futures.workspace = true
tokio.workspace = true

[lints]
workspace = true
