#!/usr/bin/env python3
"""Generate the ddd4j Reactor to ddd4r package migration manifest."""

from __future__ import annotations

import argparse
import subprocess
import xml.etree.ElementTree as ET
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class ReactorProject:
    path: str
    artifact: str
    packaging: str


SPECIAL_NAMES = {
    "ddd4j-data-jpa": "ddd4r-data-seaorm",
    "ddd4j-data-mybatis": "ddd4r-data-rbatis",
    "ddd4j-data-mybatisplus": "ddd4r-data-rbatisplus",
}

IN_PROGRESS = {
    "ddd4j",
    "ddd4j-annotation",
    "ddd4j-core",
    "ddd4j-kit",
    "ddd4j-cache",
}

API_EVIDENCE = {
    "ddd4j": ["crates/ddd4r/src/lib.rs"],
    "ddd4j-annotation": ["crates/ddd4r-annotation/src/lib.rs"],
    "ddd4j-core": ["crates/ddd4r-core/src"],
    "ddd4j-kit": ["crates/ddd4r-kit/src/lib.rs"],
    "ddd4j-cache": ["crates/ddd4r-cache/src/lib.rs"],
}

TEST_EVIDENCE = {
    "ddd4j": ["crates/ddd4r/tests/derive_contract.rs"],
    "ddd4j-annotation": ["crates/ddd4r/tests/derive_contract.rs"],
    "ddd4j-core": ["crates/ddd4r-core/tests/core_contract.rs"],
    "ddd4j-kit": ["crates/ddd4r-kit/src/lib.rs#tests"],
    "ddd4j-cache": ["crates/ddd4r-cache/src/lib.rs#tests"],
}


def local_name(element: ET.Element) -> str:
    return element.tag.rsplit("}", 1)[-1]


def direct_child(element: ET.Element, name: str) -> ET.Element | None:
    return next((child for child in element if local_name(child) == name), None)


def direct_text(element: ET.Element, name: str, default: str) -> str:
    child = direct_child(element, name)
    return child.text.strip() if child is not None and child.text else default


def collect(source: Path) -> list[ReactorProject]:
    source = source.resolve()
    projects: list[ReactorProject] = []

    def visit(directory: Path) -> None:
        pom = directory / "pom.xml"
        if not pom.is_file():
            raise FileNotFoundError(f"missing Reactor POM: {pom}")
        root = ET.parse(pom).getroot()
        relative = "." if directory == source else directory.relative_to(source).as_posix()
        artifact = direct_text(root, "artifactId", "ddd4j")
        projects.append(
            ReactorProject(
                path=relative,
                artifact=artifact,
                packaging=direct_text(root, "packaging", "jar"),
            )
        )
        modules = direct_child(root, "modules")
        if modules is None:
            return
        for module in modules:
            if local_name(module) == "module" and module.text:
                visit((directory / module.text.strip()).resolve())

    visit(source)
    return projects


def rust_name(artifact: str) -> str:
    return SPECIAL_NAMES.get(artifact, artifact.replace("ddd4j", "ddd4r", 1))


def rust_path(project: ReactorProject) -> str:
    name = rust_name(project.artifact)
    if project.path == ".":
        return "."
    first = project.path.split("/", 1)[0]
    if first in {"ddd4j-bom", "ddd4j-dependencies", "ddd4j-annotation", "ddd4j-core", "ddd4j-kit", "ddd4j-cache", "ddd4j-parent"}:
        return f"crates/{name}"
    groups = {
        "ddd4j-ddd-rules": "ddd-rules",
        "ddd4j-data": "data",
        "ddd4j-mq": "mq",
        "ddd4j-web": "web",
        "ddd4j-auth": "auth",
        "ddd4j-runtime": "runtime",
        "ddd4j-extensions": "extensions",
        "ddd4j-samples": "samples",
    }
    return f"modules/{groups[first]}/{name}"


def git_value(source: Path, *args: str) -> str:
    return subprocess.check_output(
        ["git", *args], cwd=source, text=True, stderr=subprocess.DEVNULL
    ).strip()


def quote(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def string_array(values: list[str]) -> str:
    return "[" + ", ".join(quote(value) for value in values) + "]"


def render(source: Path, projects: list[ReactorProject]) -> str:
    commit = git_value(source, "rev-parse", "HEAD")
    branch = git_value(source, "branch", "--show-current")
    lines = [
        "# Generated by tools/generate_port_manifest.py; do not edit module rows manually.",
        "manifest_version = 1",
        f"source_repository = {quote(str(source))}",
        f"source_branch = {quote(branch)}",
        f"source_commit = {quote(commit)}",
        'baseline_tag = "ddd4r-port-baseline-2026-07-21"',
        f"reactor_project_count = {len(projects)}",
        "",
    ]
    for index, project in enumerate(projects, start=1):
        status = "in_progress" if project.artifact in IN_PROGRESS else "scaffolded"
        lines.extend(
            [
                "[[module]]",
                f"index = {index}",
                f"java_artifact = {quote(project.artifact)}",
                f"java_path = {quote(project.path)}",
                f"java_packaging = {quote(project.packaging)}",
                f"rust_package = {quote(rust_name(project.artifact))}",
                f"rust_path = {quote(rust_path(project))}",
                f"status = {quote(status)}",
                f"api_evidence = {string_array(API_EVIDENCE.get(project.artifact, []))}",
                f"test_evidence = {string_array(TEST_EVIDENCE.get(project.artifact, []))}",
                'semantic_differences = []',
                "",
            ]
        )
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=Path, required=True)
    parser.add_argument("--output", type=Path, default=Path("port-manifest.toml"))
    args = parser.parse_args()
    projects = collect(args.source)
    if len(projects) != 82:
        raise SystemExit(f"expected 82 Reactor projects, found {len(projects)}")
    args.output.write_text(render(args.source.resolve(), projects), encoding="utf-8")


if __name__ == "__main__":
    main()
